# Generated by Django 4.2.5 on 2023-09-21 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_Chat', models.FilePathField()),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='matches.match', verbose_name='the related Match')),
            ],
        ),
    ]
